### ISSUE TITLE
upnp-list script bundled have error 

### ISSUE THREAD

**Issue by yamatakau08** [sidoh/easy_upnp#4]
Dear owner of easy_upnp,

I'm new to use "easy_upnp".
Firstly, I executed upnp_list sript bundled "easy_upnp" bin directory.
I faced the error message the following.
Could you advice me to resolved that?

The upnp_list script returns "Found 58 devices", so a part of "easy_upnp" works well.

Best regards,

```
yama@tnt:~/.gem/ruby/gems/easy_upnp-1.1.8/bin$ ls
./  ../  upnp-list*
yama@tnt:~/.gem/ruby/gems/easy_upnp-1.1.8/bin$ ./upnp-list
Starting SSDP search...
Found 58 devices:
                          Name                                          UUID Services
/cygdrive/c/yama/.gem/ruby/gems/easy_upnp-1.1.8/lib/easy_upnp/upnp_device.rb:70:in `fetch_device_name': Couldn't resolve device name because no endpoints are defined (RuntimeError)
        from /cygdrive/c/yama/.gem/ruby/gems/easy_upnp-1.1.8/lib/easy_upnp/upnp_device.rb:41:in `device_name'
        from ./upnp-list:38:in `block in <main>'
        from ./upnp-list:37:in `each'
        from ./upnp-list:37:in `<main>'
```

**Comment by sidoh** [comment]
Should be fixed. Please try updating to 1.1.9.

**Comment by yamatakau08** [comment]
Dear sidoh-san,

Thank you for fixing.
v1.1.9 fixed the my comments.
I had another error.
Could you fix that?

```
yama@tnt:~/.gem/ruby/gems/easy_upnp-1.1.9/bin$ ls
./  ../  upnp-list*
yama@tnt:~/.gem/ruby/gems/easy_upnp-1.1.9/bin$ ./upnp-list
Starting SSDP search...
Found 56 devices:
                          Name                                          UUID Services
                   KJ-49X8300D     uuid:8273bf4b-7776-4862-39c7-69e5cb27a19d urn:dial-multiscreen-org:service:dial:1

                   KJ-49X8300D     uuid:29d3b862-af69-1678-c821-a033a9086f3c urn:dial-multiscreen-org:service:dial:1

/cygdrive/c/yama/.gem/ruby/gems/easy_upnp-1.1.9/lib/easy_upnp/upnp_device.rb:70:in `fetch_device_name': Couldn't resolve device name because no endpoints are defined (RuntimeError)
        from /cygdrive/c/yama/.gem/ruby/gems/easy_upnp-1.1.9/lib/easy_upnp/upnp_device.rb:41:in `device_name'
        from ./upnp-list:40:in `block in <main>'
        from ./upnp-list:37:in `each'
        from ./upnp-list:37:in `<main>'
 ```

**Comment by sidoh** [comment]
I woke up realizing I'd forgotten to complete the fix before pushing.

Please try 1.1.10.
