### ISSUE TITLE
".host" method sometimes puts out error

### ISSUE THREAD

**Issue by yamatakau08** [sidoh/easy_upnp#5]
Dear Chris@sidoh san,

I run the follwoing script

```
#! /bin/ruby

require 'easy_upnp'

searcher = EasyUpnp::SsdpSearcher.new 
devices = searcher.search 'ssdp:all'

device = devices.first

p device
puts "host:#{device.host}"
```

sometimes puts out  error like this.

```
yama@tnt:~/bin/UPnP$ ./easy_upnp.rb
#<EasyUpnp::UpnpDevice:0x00000600d3cd80 @uuid="uuid:bf5d857e-6195-4cc2-ab75-f19f7dec2e79", @service_definitions=[]>
/cygdrive/c/yama/.gem/ruby/gems/easy_upnp-1.1.9/lib/easy_upnp/upnp_device.rb:37:in `host': undefined method `[]' for nil:NilClass (NoMethodError)
        from ./easy_upnp.rb:12:in `<main>'
```

**Comment by sidoh** [comment]
It looks like you have a device on your network responding to search requests without having any service endpoints.

I'd like to add some verbose logging options to the SSDP search. I'll let you know when I do that (should have time in the next few days). Would you be able to paste some output for me when I get to that?

**Comment by yamatakau08** [comment]
Thank you for your support!

`I'll let you know when I do that (should have time in the next few days).`
I'm waiting for your modification
`Would you be able to paste some output for me when I get to that?`
Of course. No problem.
