### ISSUE TITLE
"fetch_device_name" puts out error

### ISSUE THREAD

**Issue by yamatakau08** [sidoh/easy_upnp#6]
Dear Chris@sidoh san,

Thank you for fixing.
v1.1.9 fixed the my comments.
I had another error.
Could you fix that?

```
yama@tnt:~/.gem/ruby/gems/easy_upnp-1.1.9/bin$ ls
./  ../  upnp-list*
yama@tnt:~/.gem/ruby/gems/easy_upnp-1.1.9/bin$ ./upnp-list
Starting SSDP search...
Found 56 devices:
                          Name                                          UUID Services
                   KJ-49X8300D     uuid:8273bf4b-7776-4862-39c7-69e5cb27a19d urn:dial-multiscreen-org:service:dial:1

                   KJ-49X8300D     uuid:29d3b862-af69-1678-c821-a033a9086f3c urn:dial-multiscreen-org:service:dial:1

/cygdrive/c/yama/.gem/ruby/gems/easy_upnp-1.1.9/lib/easy_upnp/upnp_device.rb:70:in `fetch_device_name': Couldn't resolve device name because no endpoints are defined (RuntimeError)
        from /cygdrive/c/yama/.gem/ruby/gems/easy_upnp-1.1.9/lib/easy_upnp/upnp_device.rb:41:in `device_name'
        from ./upnp-list:40:in `block in <main>'
        from ./upnp-list:37:in `each'
        from ./upnp-list:37:in `<main>'
```

**Comment by sidoh** [comment]
Hi @yamatakau08, sorry for the super slow reply.  This slipped through the cracks.

Is this still happening for you?  I think this should be fixed in >= 1.1.10.
