### ISSUE TITLE
upnp_list puts out "Connection refused - connect(2) (Errno::ECONNREFUSED)"

### ISSUE THREAD

**Issue by yamatakau08** [sidoh/easy_upnp#7]
Dear Chris@sidoh san,

I happened to face another issue when I run upnp-list script.
Could you teach what is problem, my environment, port settings?

Best regards,

```
yama$ ./upnp-list 
Starting SSDP search...
Found 7 devices:
                          Name                                          UUID Services
Logitec RouterWANDeviceWANConnectionDevice     uuid:75802409-bccb-40e7-8e6c-fa095ecce13e urn:schemas-upnp-org:service:Layer3Forwarding:1

                     RalinkAPS     uuid:28802880-2880-1880-a880-00018e3ab5d4 urn:schemas-wifialliance-org:service:WFAWLANConfig:1

              BDR - BDZ-ZT1000     uuid:1958564F-B0B6-1FB3-8380-a8a795ad6842 urn:schemas-upnp-org:service:ContentDirectory:1
                                                                             urn:schemas-upnp-org:service:ConnectionManager:1
                                                                             urn:schemas-xsrs-org:service:X_ScheduledRecording:2
                                                                             urn:schemas-xsrs-org:service:X_ScheduledRecordingExt:1
                                                                             urn:schemas-s-bras-org:service:X_PvrControl:1

                    BDZ-ET2000     uuid:1958564F-B0B6-1FB3-8380-78617ce13c0e urn:schemas-upnp-org:service:ContentDirectory:1
                                                                             urn:schemas-upnp-org:service:ConnectionManager:1
                                                                             urn:schemas-xsrs-org:service:X_ScheduledRecording:2
                                                                             urn:schemas-xsrs-org:service:X_ScheduledRecordingExt:1
                                                                             urn:schemas-s-bras-org:service:X_PvrControl:1

/Library/Ruby/Gems/2.0.0/gems/socksify-1.7.0/lib/socksify.rb:178:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
    from /Library/Ruby/Gems/2.0.0/gems/socksify-1.7.0/lib/socksify.rb:178:in `initialize'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:313:in `open_http'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
    from /Library/Ruby/Gems/2.0.0/gems/easy_upnp-1.1.9/lib/easy_upnp/upnp_device.rb:73:in `fetch_device_name'
    from /Library/Ruby/Gems/2.0.0/gems/easy_upnp-1.1.9/lib/easy_upnp/upnp_device.rb:41:in `device_name'
    from ./upnp-list:40:in `block in <main>'
    from ./upnp-list:37:in `each'
    from ./upnp-list:37:in `<main>
```

**Comment by sidoh** [comment]
Yeah -- so these are all basically the same underlying issue.

In order to determine the "name" of the service, it's fetching the service definition from the endpoint communicated by SSDP and extracting a field from it.

It looks like you have a few strange devices on your network responding to UPnP searches that don't actually have any services. Also appears you have a few that are responding to searches with service definition endpoints that are unreachable. 1.1.10 should at least allow `upnp-list` to complete without any errors.

I can add a debug flag to the SSDP search. Would you be willing to paste the output from that? It'd help me debug.

**Comment by yamatakau08** [comment]
Dear Chris@sidoh san,

I downloaded v1.1.10 and run upnp-list script.
The output is following..

```
yama$ pwd
/Library/Ruby/Gems/2.0.0/gems/easy_upnp-1.1.10/bin
yama$ ./upnp-list 
Starting SSDP search...
Found 6 devices:
                          Name                                          UUID Services
Logitec RouterWANDeviceWANConnectionDevice     uuid:75802409-bccb-40e7-8e6c-fa095ecce13e urn:schemas-upnp-org:service:Layer3Forwarding:1

                     RalinkAPS     uuid:28802880-2880-1880-a880-00018e3ab5d4 urn:schemas-wifialliance-org:service:WFAWLANConfig:1

   *** Error fetching name ***     uuid:03010100-0200-85c6-002e-64f0a08d991a urn:schemas-sony-com:service:X_Telepathy:1

                    BDZ-ET2000     uuid:1958564F-B0B6-1FB3-8380-78617ce13c0e urn:schemas-upnp-org:service:ContentDirectory:1
                                                                             urn:schemas-upnp-org:service:ConnectionManager:1
                                                                             urn:schemas-xsrs-org:service:X_ScheduledRecording:2
                                                                             urn:schemas-xsrs-org:service:X_ScheduledRecordingExt:1
                                                                             urn:schemas-s-bras-org:service:X_PvrControl:1

Logitec RouterWANDeviceWANConnectionDevice     uuid:c4131cbd-0408-463d-91b0-38dd1ee22fd6 urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1

Logitec RouterWANDeviceWANConnectionDevice     uuid:5f75f342-9f96-4ecc-9dbd-6f981efc3f14 urn:schemas-upnp-org:service:WANIPConnection:1
```

**Comment by sidoh** [comment]
Cool -- seems like it works then, right?

Whatever device is serving `urn:schemas-sony-com:service:X_Telepathy:1` is broadcasting a service endpoint that is unreachable.

Does this fix your problem? Can we close the issue?

**Comment by yamatakau08** [comment]
Thank you for reply.

About bundle script, we can close this issue.

Could you advice me how I judge if "device" variable have host name #5?
Do I need to check if "device.host" is nil?
After that, I execute process what I want to do?

It's better we used #5 issue board.

**Comment by sidoh** [comment]
Thanks!
