### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by arjunmenon** [sidoh/easy_upnp#8]
I get this error - `RuntimeError: eventmachine not initialized: evma_connect_to_server`
RPi3 with `gmediarender-resurrect`
```ruby
irb(main):001:0> require 'easy_upnp'
=> true
irb(main):002:0> 
irb(main):003:0* searcher = EasyUpnp::SsdpSearcher.new 
=> #<EasyUpnp::SsdpSearcher:0x14ecbf0 @options={:timeout=>2, :mx=>1, :repeat_queries=>1}>
irb(main):004:0> devices = searcher.search 'ssdp:all'
=> [#<EasyUpnp::UpnpDevice:0x1374450 @uuid="uuid:644acae08213ec4b4ef81c9384e2df7a", @service_definitions=[{:location=>"http://192.168.1.6:49494/description.xml", :st=>"urn:schemas-upnp-org:service:AVTransport:1"}, {:location=>"http://192.168.1.6:49494/description.xml", :st=>"urn:schemas-upnp-org:service:ConnectionManager:1"}, {:location=>"http://192.168.1.6:49494/description.xml", :st=>"urn:schemas-upnp-org:service:RenderingControl:1"}]>]
irb(main):005:0> device = devices.first
=> #<EasyUpnp::UpnpDevice:0x1374450 @uuid="uuid:644acae08213ec4b4ef81c9384e2df7a", @service_definitions=[{:location=>"http://192.168.1.6:49494/description.xml", :st=>"urn:schemas-upnp-org:service:AVTransport:1"}, {:location=>"http://192.168.1.6:49494/description.xml", :st=>"urn:schemas-upnp-org:service:ConnectionManager:1"}, {:location=>"http://192.168.1.6:49494/description.xml", :st=>"urn:schemas-upnp-org:service:RenderingControl:1"}]>
irb(main):006:0> device.all_services
=> ["urn:schemas-upnp-org:service:AVTransport:1", "urn:schemas-upnp-org:service:ConnectionManager:1", "urn:schemas-upnp-org:service:RenderingControl:1"]
irb(main):007:0> service = device.service 'urn:schemas-upnp-org:service:AVTransport:1'
=> #<EasyUpnp::DeviceControlPoint:0x19e07c8 @urn="urn:schemas-upnp-org:service:AVTransport:1", @service_endpoint="http://192.168.1.6:49494/upnp/control/rendertransport1", @definition="<?xml version=\"1.0\"?>\.......
...
...
irb(main):008:0> 
irb(main):009:0>service.service_methods
=> [:GetCurrentTransportActions, :GetDeviceCapabilities, :GetMediaInfo, :GetPositionInfo, :GetTransportInfo, :GetTransportSettings, :Pause, :Play, :Seek, :SetAVTransportURI, :Stop, :SetNextAVTransportURI]
irb(main):012:0> service.Pause
RuntimeError: eventmachine not initialized: evma_connect_to_server
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:677:in `connect_server'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:677:in `bind_connect'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/em-http-request-1.1.5/lib/em-http/http_connection.rb:55:in `activate_connection'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/em-http-request-1.1.5/lib/em-http/http_connection.rb:92:in `setup_request'
	from (eval):6:in `post'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib/httpi/adapter/em_http.rb:50:in `block in request'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib/httpi/adapter/em_http.rb:68:in `_request'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib/httpi/adapter/em_http.rb:50:in `request'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib/httpi.rb:161:in `request'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib/httpi.rb:133:in `post'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:94:in `block in call_with_logging'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/request_logger.rb:12:in `log'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:94:in `call_with_logging'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:54:in `call'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/client.rb:36:in `call'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/easy_upnp-1.1.11/lib/easy_upnp/control_point/client_wrapper.rb:54:in `call'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/easy_upnp-1.1.11/lib/easy_upnp/control_point/service_method.rb:31:in `call_method'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/easy_upnp-1.1.11/lib/easy_upnp/control_point/device_control_point.rb:205:in `block in define_service_method'
	from (irb):12
	from /home/pi/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'irb(main):013:0> ^C
```

**Comment by sidoh** [comment]
Can you try running

```
HTTPI.adapter = :net_http
```

and then re-trying?

**Comment by arjunmenon** [comment]
Reran exactly
```ruby
irb(main):015:0> HTTPI.adapter = :net_http
=> :net_http

irb(main):017:0> devices = searcher.search 'ssdp:all'
=> [#<EasyUpnp::UpnpDevice:0x13170c0 @uuid="uuid:644acae08213ec4b4ef81c9384e2df7a", @service_definitions=[{:location=>"http://192.168.1.6:49494/description.xml", :st=>"urn:schemas-upnp-org:service:AVTransport:1"}, {:location=>"http://192.168.1.6:49494/description.xml", :st=>"urn:schemas-upnp-org:service:ConnectionManager:1"}, {:location=>"http://192.168.1.6:49494/description.xml", :st=>"urn:schemas-upnp-org:service:RenderingControl:1"}]>, #<EasyUpnp::UpnpDevice:0x1316e50 @uuid="uuid:3272ae29-625e-e3fc-0000-00007ee16991", @service_definitions=[{:location=>"http://192.168.1.3:58645/dev/3272ae29-625e-e3fc-0000-00007ee16991/desc.xml", :st=>"urn:schemas-upnp-org:service:RenderingControl:1"}, {:location=>"http://192.168.1.3:58645/dev/3272ae29-625e-e3fc-0000-00007ee16991/desc.xml", :st=>"urn:schemas-upnp-org:service:AVTransport:1"}, {:location=>"http://192.168.1.3:58645/dev/3272ae29-625e-e3fc-0000-00007ee16991/desc.xml", :st=>"urn:schemas-upnp-org:service:ConnectionManager:1"}]>, #<EasyUpnp::UpnpDevice:0x1316be0 @uuid="uuid:3272ae29-625e-e3fc-0000-00003a523391", @service_definitions=[{:location=>"http://192.168.1.3:58645/dev/3272ae29-625e-e3fc-0000-00003a523391/desc.xml", :st=>"urn:schemas-upnp-org:service:ContentDirectory:1"}, {:location=>"http://192.168.1.3:58645/dev/3272ae29-625e-e3fc-0000-00003a523391/desc.xml", :st=>"urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1"}, {:location=>"http://192.168.1.3:58645/dev/3272ae29-625e-e3fc-0000-00003a523391/desc.xml", :st=>"urn:schemas-upnp-org:service:ConnectionManager:1"}]>]

irb(main):022:0> service.Pause
Savon::SOAPFault: (s:Client) UPnPError
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/response.rb:85:in `raise_soap_and_http_errors!'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/response.rb:14:in `initialize'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:72:in `new'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:72:in `create_response'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:58:in `call'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/client.rb:36:in `call'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/easy_upnp-1.1.11/lib/easy_upnp/control_point/client_wrapper.rb:54:in `call'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/easy_upnp-1.1.11/lib/easy_upnp/control_point/service_method.rb:31:in `call_method'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/easy_upnp-1.1.11/lib/easy_upnp/control_point/device_control_point.rb:205:in `block in define_service_method'
	from (irb):22
	from /home/pi/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'

```
This time `searcher.search` returned more results.

**Comment by sidoh** [comment]
Ugh. I HTTPI's global state is so gross. I wonder why it was set to eventmachine for you by default. I think it's http_client by default for me. Are you loading other gems in this environment?

You probably have to pass an argument to `Pause`. Maybe try 

```ruby
service.Pause(InstanceID: 0)
```

To get a list of arguments for a service method, you can do:

```ruby
service.method_args(:Pause)
```

**Comment by arjunmenon** [comment]
Darn me!
Can't forget that arguments.

It worked man! Thank you. It feels sweet.

Didn't require any other gems. So the thing to note is the adapter should be `net_http` always, right?

**Comment by sidoh** [comment]
Sweet.

Yeah, I did not build this to work with eventmachine. eventmachine is built for asynchronous stuff, and I specifically wanted this library to be synchronous.

Can you start a fresh irb and run this for me? Should hopefully reveal any differences in our environments:

```
irb(main):001:0> require 'easy_upnp'; Gem.loaded_specs.each { |k,v| puts "#{v.name}, #{v.version}" }; nil
did_you_mean, 1.0.0
socksify, 1.7.0
httpi, 2.4.2
wasabi, 3.5.0
gyoku, 1.3.1
savon, 2.11.1
easy_upnp, 1.1.11
mini_portile2, 2.1.0
nokogiri, 1.7.0.1
rack, 1.6.5
akami, 1.3.1
builder, 3.2.3
nori, 2.6.0
psych, 2.0.17
bigdecimal, 1.2.8
=> nil
irb(main):002:0>
```

**Comment by arjunmenon** [comment]
```ruby
irb(main):001:0> require 'easy_upnp'; Gem.loaded_specs.each { |k,v| puts "#{v.name}, #{v.version}" }; nil
did_you_mean, 1.0.0
rake, 10.4.2
nori, 2.6.0
rack, 2.0.1
socksify, 1.7.1
httpi, 2.4.2
mini_portile2, 2.1.0
nokogiri, 1.7.1
wasabi, 3.5.0
builder, 3.2.3
gyoku, 1.3.1
savon, 2.11.1
easy_upnp, 1.1.11
akami, 1.3.1
psych, 2.0.17
bigdecimal, 1.2.8
=> nil
irb(main):002:0> 
```
These are the differences
```
rake, 10.4.2
rack, 2.0.1
socksify, 1.7.1
nokogiri, 1.7.1
```

hey something strange happened, 
I ran this
```ruby
service3 = device.service 'urn:schemas-upnp-org:service:RenderingControl:1'
irb(main):019:0> service3.service_methods
=> [:GetBlueVideoBlackLevel, :GetBlueVideoGain, :GetBrightness, :GetColorTemperature, :GetContrast, :GetGreenVideoBlackLevel, :GetGreenVideoGain, :GetHorizontalKeystone, :GetLoudness, :GetMute, :GetRedVideoBlackLevel, :GetRedVideoGain, :GetSharpness, :GetVerticalKeystone, :GetVolume, :GetVolumeDB, :GetVolumeDBRange, :ListPresets, :SetMute, :SetVolume, :SetVolumeDB]
irb(main):023:0> service3.method_args(:SetMute)
=> [:InstanceID, :Channel, :DesiredMute]
irb(main):024:0> service3.SetMute(InstanceID: 0)
EOFError: end of file reached

irb(main):026:0> service3.SetMute(InstanceID: 0, DesiredMute: 100)
Errno::ECONNREFUSED: Failed to open TCP connection to 192.168.1.6:49494 (Connection refused - connect(2) for "192.168.1.6" port 49494)
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib/httpi/adapter/net_http.rb:85:in `do_request'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib/httpi/adapter/net_http.rb:38:in `request'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib/httpi.rb:161:in `request'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib/httpi.rb:133:in `post'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:94:in `block in call_with_logging'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/request_logger.rb:12:in `log'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:94:in `call_with_logging'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:54:in `call'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/savon-2.11.1/lib/savon/client.rb:36:in `call'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/easy_upnp-1.1.11/lib/easy_upnp/control_point/client_wrapper.rb:54:in `call'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/easy_upnp-1.1.11/lib/easy_upnp/control_point/service_method.rb:31:in `call_method'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/easy_upnp-1.1.11/lib/easy_upnp/control_point/device_control_point.rb:205:in `block in define_service_method'
	from (irb):26
	from /home/pi/.r3 = device.service 'urn:schemas-upnp-org:service:RenderingControl:1'^C

```
I was trying to control the volumes. The first service methods did not have the volume options. So ran a different `device.service`

Now the Raspberry Pi is completely shut. `gmediarender` is just off. Android said it lost connection.

Rebooted Pi and did not find the gmediarender to autostart. So had to run `gmediarender defaults`, but now Android is streaming but Pi is not receiving anything.

**Comment by sidoh** [comment]
So this is apparently the ordering of adapters HTTPI tries ([source](https://github.com/savonrb/httpi/blob/master/lib/httpi/adapter.rb#L16))

```
 LOAD_ORDER = [:httpclient, :curb, :em_http, :excon, :http, :net_http, :net_http_persistent]
```

It's infuriating that `:em_http` is before `:net_http`, which is Ruby's baked-in HTTP client. Are you able to set it to `:em_http`? I get an error:

```
irb(main):018:0> HTTPI.adapter = :em_http
LoadError: cannot load such file -- em-synchrony
	from /Users/cmullins/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Users/cmullins/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Users/cmullins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib/httpi/adapter.rb:51:in `block in load_adapter'
	from /Users/cmullins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib/httpi/adapter.rb:50:in `each'
	from /Users/cmullins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib/httpi/adapter.rb:50:in `load_adapter'
	from /Users/cmullins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib/httpi/adapter.rb:29:in `use='
	from /Users/cmullins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/httpi-2.4.2/lib/httpi.rb:174:in `adapter='
	from (irb):18
	from /Users/cmullins/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
```

It looks like you crashed the server, lol. My guess is that the server is bad at input validation and is not robust to `:DesiredMute` not being specified.

I'd recommend turning argument validation on:

```ruby
client = device.service('urn:schemas-upnp-org:service:ContentDirectory:1') do |o|
  o.validate_arguments = true
end
```

Then you'll get exceptions when you're missing arguments or they have invalid values.

**Comment by arjunmenon** [comment]
```
irb(main):004:0> HTTPI.adapter = :em_http
=> :em_http
irb(main):005:0> 

```
It did not return any error.

I turned on validation, which is pretty helpful. However, 
```ruby
irb(main):084:0> service2.SetMute(InstanceID: '0')
ArgumentError: Invalid value for argument InstanceID: 0 is the wrong type. Should be one of: [Integer]
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/easy_upnp-1.1.11/lib/easy_upnp/control_point/service_method.rb:27:in `rescue in block in call_method'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/easy_upnp-1.1.11/lib/easy_upnp/control_point/service_method.rb:24:in `block in call_method'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/easy_upnp-1.1.11/lib/easy_upnp/control_point/service_method.rb:22:in `each'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/easy_upnp-1.1.11/lib/easy_upnp/control_point/service_method.rb:22:in `call_method'
	from /home/pi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/easy_upnp-1.1.11/lib/easy_upnp/control_point/device_control_point.rb:205:in `block in define_service_method'
	from (irb):84
	from /home/pi/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
irb(main):085:0> service2.SetMute(InstanceID: 0)
EOFError: end of file reached

```
It still breaks.
But the `SetVolume` method works. So that's that.

I also noticed that `next` and `prev` track changing isn't available in any of the services.
Question, is it available? Supported in library? Or Upnp doesn't know how do it?
More question, all this I have been trying it out from the Pi terminal. But can't access anything from my desktop. Any hack? Ideally, it should have been, right?

**Comment by sidoh** [comment]
I guess it doesn't yell at you for not providing some arguments. You need to specify `Channel` and `DesiredMute` here as well. `SetMute` is named confusingly, I think. It means "set mute to the specified value", not "turn on or toggle mute".

This library is a general UPnP library. Clients are constructed dynamically based on service definitions provided by the server. The services you're using are standard UPnP services. You're using the [RenderingControl](http://upnp.org/specs/av/UPnP-av-RenderingControl-v1-Service.pdf) service. Playback control is provided by the [AVTransport](http://upnp.org/specs/av/UPnP-av-AVTransport-v1-Service.pdf) service.

Yes, it should show up. Are you able to verify that your desktop can see UPnP devices in some other tool? Could just be a networking thing.

**Comment by sidoh** [comment]
@arjunmenon were you able to figure this one out?  Can we close the ticket?

**Comment by arjunmenon** [comment]
Worked like a charm. 
Thanks.

![](http://www.reactiongifs.com/wp-content/uploads/2013/04/tip-hat.gif)
